# Generated by Django 4.1.4 on 2023-01-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('foto', models.ImageField(null=True, upload_to='perfiles/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('pais', models.CharField(choices=[('SN', 'Seleccionar país de residencia'), ('CUB', 'Cuba'), ('USA', 'Estados Unidos'), ('ESP', 'España')], default='SN', max_length=200)),
                ('telefono', models.CharField(max_length=200, null=True, unique=True)),
                ('descripcion', models.TextField(null=True)),
                ('sexo', models.CharField(choices=[('S', 'Sin especificar'), ('H', 'Hombre'), ('M', 'Mujer')], default='S', max_length=1)),
                ('is_verificado', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
