# Generated by Django 4.1.4 on 2023-01-04 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('foto', models.ImageField(upload_to='portadas_campismos/')),
                ('descripcion', models.CharField(max_length=1000)),
                ('precioTA', models.IntegerField()),
                ('precioTB', models.IntegerField()),
                ('categoria', models.CharField(choices=[('1', 'Primera'), ('2', 'Segunda'), ('3', 'Tercera'), ('4', 'Cuarta')], default='4', max_length=1)),
                ('tipoTurismo', models.CharField(choices=[('N', 'Nacional'), ('I', 'Internacional'), ('A', 'Ambos')], default='A', max_length=2)),
                ('transporteIncluido', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Campismo',
                'verbose_name_plural': 'Campismos',
            },
        ),
        migrations.CreateModel(
            name='ComentarioExcursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=1200)),
                ('padre', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ComentarioExcursion',
                'verbose_name_plural': 'ComentarioExcursiones',
            },
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('foto', models.ImageField(upload_to='portadas_excursiones/')),
                ('destino', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=2000)),
                ('precio', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Excursion',
                'verbose_name_plural': 'Excursiones',
            },
        ),
        migrations.CreateModel(
            name='HabitacionCampismo',
            fields=[
                ('idHab', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cantidadHuespedes', models.CharField(choices=[('4', 'Cuatro'), ('8', 'Ocho')], default='4', max_length=1)),
                ('estado', models.CharField(choices=[('D', 'Disponible'), ('N', 'No disponible')], default='D', max_length=1)),
            ],
            options={
                'verbose_name': 'HabitacionCampismo',
                'verbose_name_plural': 'HabitacionesCampismo',
            },
        ),
        migrations.CreateModel(
            name='InstanciaExcursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('capacidad', models.IntegerField()),
                ('estado', models.CharField(choices=[('P', 'Pasada'), ('A', 'Activa')], default='A', max_length=2)),
            ],
            options={
                'verbose_name': 'InstanciaExcursion',
                'verbose_name_plural': 'InstanciaExcursiones',
            },
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefonos', models.TextField()),
                ('h_lunes', models.CharField(max_length=150)),
                ('h_martes', models.CharField(max_length=150)),
                ('h_miercoles', models.CharField(max_length=150)),
                ('h_jueves', models.CharField(max_length=150)),
                ('h_viernes', models.CharField(max_length=150)),
                ('h_sabado', models.CharField(max_length=150)),
                ('h_domingo', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Oficina',
                'verbose_name_plural': 'Oficinas',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
            },
        ),
        migrations.CreateModel(
            name='ReservaCampismo',
            fields=[
                ('idReserva', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('estado', models.CharField(choices=[('ET', 'En tiempo'), ('P', 'Pasada'), ('C', 'Cancelada')], default='ET', max_length=2)),
                ('fechaEntrada', models.DateField()),
                ('fechaSalida', models.DateField()),
                ('cantP', models.IntegerField()),
            ],
            options={
                'verbose_name': 'ReservaCampismo',
                'verbose_name_plural': 'ReservasCampismo',
            },
        ),
        migrations.CreateModel(
            name='ReservaExcursion',
            fields=[
                ('idReserva', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('estado', models.CharField(choices=[('ET', 'En tiempo'), ('P', 'Pasada'), ('C', 'Cancelada')], default='ET', max_length=2)),
                ('cantP', models.IntegerField()),
            ],
            options={
                'verbose_name': 'ReservaExcursion',
                'verbose_name_plural': 'ReservaExcursiones',
            },
        ),
        migrations.CreateModel(
            name='ValoracionCampismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.IntegerField()),
                ('comentario', models.CharField(max_length=1200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('campismo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campismo_valoracion', to='campismo.campismo')),
            ],
            options={
                'verbose_name': 'ValoracionCampismo',
                'verbose_name_plural': 'ValoracionesCampismo',
            },
        ),
    ]
